
[functions.member-events]
enabled = true
verify_jwt = true
import_map = "./functions/member-events/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/member-events/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/member-events/*.html" ]

[functions.prayer-confirmation]
enabled = true
verify_jwt = true
import_map = "./functions/prayer-confirmation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/prayer-confirmation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/prayer-confirmation/*.html" ]
